import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";

import Footer from "../src/components/Footer";

import React, { useState, useEffect } from "react";
import Hero from "../src/components/Hero";
import About from "../src/components/About";
import Projects from "../src/components/Projects";
import Contact from "../src/components/Contact";

import { PortfolioProvider } from "../src/context/context";

import {
  heroData,
  aboutData,
  projectsData,
  contactData,
  footerData,
} from "../data";
import NewLanding from "../src/components/NewLanding";
import Skills from "../src/components/skills";
import WorkEducation from "../src/components/WorkEducation";

export default function Home() {
  const [hero, setHero] = useState({});
  const [about, setAbout] = useState({});
  const [projects, setProjects] = useState([]);
  const [contact, setContact] = useState({});
  const [footer, setFooter] = useState({});

  useEffect(() => {
    setHero({ ...heroData });
    setAbout({ ...aboutData });
    setProjects([...projectsData]);
    setContact({ ...contactData });
    setFooter({ ...footerData });
  }, []);

  return (
    <PortfolioProvider value={{ hero, about, projects, contact, footer }}>
      {/* <Footer /> */}

      <div>
        <Head>
          <title>Shivam Gupta</title>
          <meta name="Portfolio" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          {" "}
          <NewLanding />
          {/* <Hero /> */}
          <Skills />
          {/* <WorkEducation /> */}
          <About />
          <Projects />
          <Contact />
          <Footer />
        </main>

        <footer></footer>
      </div>
    </PortfolioProvider>
  );
}
